import 'dart:math' as math;

import 'package:flutter/cupertino.dart';
import 'package:language_parser_desktop/components/border/border.dart';
import 'package:language_parser_desktop/components/border/hdash.dart';
import 'package:language_parser_desktop/components/buttons/phonetic_button.dart';
import 'package:language_parser_desktop/components/buttons/t_button.dart';
import 'package:language_parser_desktop/features/language_phonetics/language_phonetics_header.dart';
import 'package:language_parser_desktop/util/layout.dart';

import '../../services/language_service.dart';

class LanguagePhoneticsPlumonicConsonants extends StatelessWidget {
  final bool disabled;
  final ListOfLanguagePhonemes phonemes;
  final Function(String) onPress;
  static const List<String> rowHeaders = [
    "Nasal",
    "Plosive",
    "Sibilant affricate",
    "Non-sibilant affricate",
    "Sibilant fricative",
    "Non-sibilant fricative",
    "Approximant",
    "Tap/flap",
    "Trill",
    "Lateral affricate",
    "Lateral fricative",
    "Lateral approximant",
    "Lateral tap/flap",
  ];

  const LanguagePhoneticsPlumonicConsonants(
      {super.key, required this.disabled, required this.phonemes, required this.onPress});

  @override
  Widget build(BuildContext context) {
    return LayoutBuilder(builder: (context, constraints) {
      final cWidth = measureTextWidth('-', context);
      final rowHeaderCharacters = rowHeaders.fold(0, (p, s) => math.max(p, s.length));
      var delta = ((constraints.maxWidth) % (cWidth * 12));
      final rowHeaderLength =
          math.max(0, rowHeaderCharacters - 0 - (delta / cWidth).floorToDouble()) * cWidth + delta % cWidth;

      return Column(
        children: [
          Table(
            columnWidths: {0: FlexColumnWidth(), 1: FixedColumnWidth(cWidth)},
            children: [
              TableRow(children: [Center(child: LPhHeader(header: '--- PLUMONIC CONSONANTS ---')), DBorder(data: '|')])
            ],
          ),
          Table(
            columnWidths: {
              0: FixedColumnWidth(rowHeaderLength),
              1: FixedColumnWidth(cWidth),
              2: FlexColumnWidth(),
              3: FixedColumnWidth(cWidth)
            },
            children: [
              TableRow(children: [HDash(), DBorder(data: '+'), HDash(), DBorder(data: '+')])
            ],
          ),
          Table(
            columnWidths: {
              0: FixedColumnWidth(rowHeaderLength),
              1: FixedColumnWidth(cWidth),
              2: FlexColumnWidth(2.5),
              3: FixedColumnWidth(cWidth),
              4: FixedColumnWidth(cWidth),
              5: FixedColumnWidth(cWidth),
              6: FixedColumnWidth(cWidth),
              7: FlexColumnWidth(5),
              8: FixedColumnWidth(cWidth),
              9: FixedColumnWidth(cWidth),
              10: FixedColumnWidth(cWidth),
              11: FixedColumnWidth(cWidth),
              12: FixedColumnWidth(cWidth),
              13: FlexColumnWidth(2.5),
              14: FixedColumnWidth(cWidth),
              15: FixedColumnWidth(cWidth),
              16: FlexColumnWidth(2),
              17: FixedColumnWidth(cWidth),
            },
            children: [
              TableRow(children: [
                Container(alignment: Alignment.centerRight, child: LPhHeader(header: 'Place >')),
                DBorder(data: '|'),
                Center(child: LPhHeader(header: 'Labial')),
                Container(),
                DBorder(data: '|'),
                Container(),
                Container(),
                Center(child: LPhHeader(header: 'Coronal')),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
                Container(),
                Center(child: LPhHeader(header: 'Dorsal')),
                DBorder(data: '|'),
                Container(),
                Center(child: LPhHeader(header: 'Laryngeal')),
                DBorder(data: '|'),
              ])
            ],
          ),
          Table(
            columnWidths: {
              0: FixedColumnWidth(rowHeaderLength),
              1: FixedColumnWidth(cWidth),
              2: FlexColumnWidth(),
              3: FixedColumnWidth(cWidth),
              4: FlexColumnWidth(),
              5: FixedColumnWidth(cWidth),
              6: FlexColumnWidth(),
              7: FixedColumnWidth(cWidth),
              8: FlexColumnWidth(),
              9: FixedColumnWidth(cWidth),
              10: FlexColumnWidth(),
              11: FixedColumnWidth(cWidth),
              12: FlexColumnWidth(),
              13: FixedColumnWidth(cWidth),
              14: FlexColumnWidth(),
              15: FixedColumnWidth(cWidth),
              16: FlexColumnWidth(),
              17: FixedColumnWidth(cWidth),
              18: FlexColumnWidth(),
              19: FixedColumnWidth(cWidth),
              20: FlexColumnWidth(),
              21: FixedColumnWidth(cWidth),
              22: FlexColumnWidth(),
              23: FixedColumnWidth(cWidth),
              24: FlexColumnWidth(),
              25: FixedColumnWidth(cWidth),
            },
            children: [
              TableRow(children: [
                Container(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
              ]),
              TableRow(children: [
                LPhHeader(header: ' v Manner'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Bilabial', short: 'BL'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Labio-dental', short: 'LD'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Linguo-labial', short: 'LL'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Dental', short: 'Den'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Alveolar', short: 'Alv'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Post-alveolar', short: 'PA'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Retro-flex', short: 'RF'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Palatal', short: 'Plt'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Velar', short: 'Vel'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Uvular', short: 'Uv'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Pharyngeal/epi-glottal', short: 'P/EG'),
                DBorder(data: '|'),
                CLPhHeader(header: 'Glottal', short: 'Gl'),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
              ])
            ],
          ),
          Table(columnWidths: {
            0: FixedColumnWidth(rowHeaderLength),
            1: FixedColumnWidth(cWidth),
            2: FlexColumnWidth(0.5),
            3: FlexColumnWidth(0.5),
            4: FixedColumnWidth(cWidth),
            5: FlexColumnWidth(1),
            6: FixedColumnWidth(cWidth),
            7: FlexColumnWidth(1),
            8: FixedColumnWidth(cWidth),
            9: FlexColumnWidth(0.5),
            10: FlexColumnWidth(1),
            11: FixedColumnWidth(cWidth),
            12: FixedColumnWidth(cWidth),
            13: FlexColumnWidth(1),
            14: FlexColumnWidth(0.5),
            15: FixedColumnWidth(cWidth),
            16: FlexColumnWidth(0.5),
            17: FlexColumnWidth(0.5),
            18: FixedColumnWidth(cWidth),
            19: FlexColumnWidth(0.5),
            20: FlexColumnWidth(0.5),
            21: FixedColumnWidth(cWidth),
            22: FlexColumnWidth(0.5),
            23: FlexColumnWidth(0.5),
            24: FixedColumnWidth(cWidth),
            25: FlexColumnWidth(1),
            26: FixedColumnWidth(cWidth),
            27: FlexColumnWidth(1),
            28: FixedColumnWidth(cWidth),
            29: FlexColumnWidth(1),
            30: FixedColumnWidth(cWidth),
          }, children: [
            TableRow(children: [
              Center(child: CLPhHeader(header: rowHeaders[0])),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'm̥', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'm', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ɱ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'n̼', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              Container(),
              CPhoneticButton(phonetic: 'n̥', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              Container(),
              Container(),
              CPhoneticButton(phonetic: 'n', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              Container(),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ɳ̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'ɳ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ɲ̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'ɲ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ŋ̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'ŋ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ɴ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              Container(),
              Container(),
              Container(),
              DBorder(data: '|'),
            ]),
            TableRow(children: [
              HDash(),
              DBorder(data: '+'),
              HDash(),
              HDash(),
              DBorder(data: '+'),
              HDash(),
              DBorder(data: '+'),
              HDash(),
              DBorder(data: '+'),
              HDash(),
              HDash(),
              HDash(),
              HDash(),
              HDash(),
              HDash(),
              DBorder(data: '+'),
              HDash(),
              HDash(),
              DBorder(data: '+'),
              HDash(),
              HDash(),
              DBorder(data: '+'),
              HDash(),
              HDash(),
              DBorder(data: '+'),
              HDash(),
              DBorder(data: '+'),
              HDash(),
              DBorder(data: '+'),
              HDash(),
              DBorder(data: '+'),
            ]),
          ]),
          Table(
            columnWidths: {
              0: FixedColumnWidth(rowHeaderLength),
              1: FixedColumnWidth(cWidth),
              2: FlexColumnWidth(0.5),
              3: FlexColumnWidth(0.5),
              4: FixedColumnWidth(cWidth),
              5: FlexColumnWidth(0.5),
              6: FlexColumnWidth(0.5),
              7: FixedColumnWidth(cWidth),
              8: FlexColumnWidth(0.5),
              9: FlexColumnWidth(0.5),
              10: FixedColumnWidth(cWidth),
              11: FlexColumnWidth(0.5),
              12: FlexColumnWidth(1),
              13: FixedColumnWidth(cWidth),
              14: FixedColumnWidth(cWidth),
              15: FlexColumnWidth(1),
              16: FlexColumnWidth(0.5),
              17: FixedColumnWidth(cWidth),
              18: FlexColumnWidth(0.5),
              19: FlexColumnWidth(0.5),
              20: FixedColumnWidth(cWidth),
              21: FlexColumnWidth(0.5),
              22: FlexColumnWidth(0.5),
              23: FixedColumnWidth(cWidth),
              24: FlexColumnWidth(0.5),
              25: FlexColumnWidth(0.5),
              26: FixedColumnWidth(cWidth),
              27: FlexColumnWidth(0.5),
              28: FlexColumnWidth(0.5),
              29: FixedColumnWidth(cWidth),
              30: FlexColumnWidth(1),
              31: FixedColumnWidth(cWidth),
              32: FlexColumnWidth(1),
              33: FixedColumnWidth(cWidth),
            },
            children: [
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[1])),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'p', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'b', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'p̪', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'b̪', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 't̼', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'd̼', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 't', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                Container(),
                CPhoneticButton(phonetic: 'd', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʈ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɖ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'c', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɟ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'k', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'g', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'q', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɢ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʡ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʔ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                HDash(),
                HDash(),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
              ]),
            ],
          ),
          Table(columnWidths: {
            0: FixedColumnWidth(rowHeaderLength),
            1: FixedColumnWidth(cWidth),
            2: FixedColumnWidth(cWidth),
            3: FlexColumnWidth(3),
            4: FixedColumnWidth(cWidth),
            5: FixedColumnWidth(cWidth),
            6: FlexColumnWidth(1),
            7: FixedColumnWidth(cWidth),
            8: FlexColumnWidth(1),
            9: FixedColumnWidth(cWidth),
            10: FlexColumnWidth(0.5),
            11: FlexColumnWidth(0.5),
            12: FixedColumnWidth(cWidth),
            13: FlexColumnWidth(0.5),
            14: FlexColumnWidth(0.5),
            15: FixedColumnWidth(cWidth),
            16: FlexColumnWidth(0.5),
            17: FlexColumnWidth(0.5),
            18: FixedColumnWidth(cWidth),
            19: FixedColumnWidth(cWidth),
            20: FlexColumnWidth(4),
            21: FixedColumnWidth(cWidth),
            22: FixedColumnWidth(cWidth),
            23: FixedColumnWidth(cWidth),
          }, children: [
            TableRow(children: [
              Center(child: CLPhHeader(header: rowHeaders[2])),
              DBorder(data: '|'),
              Container(),
              Container(),
              Container(),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ʦ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              Container(),
              CPhoneticButton(phonetic: 'ʣ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ʧ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'ʤ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ʈ͡ʂ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'ɖ͡ʐ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ʨ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'ʥ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              Container(),
              Container(),
              Container(),
              Container(),
              DBorder(data: '|'),
            ]),
          ]),
          Table(
            columnWidths: {
              0: FixedColumnWidth(rowHeaderLength),
              1: FixedColumnWidth(cWidth),
              2: FlexColumnWidth(0.5),
              3: FlexColumnWidth(0.5),
              4: FixedColumnWidth(cWidth),
              5: FlexColumnWidth(0.5),
              6: FlexColumnWidth(0.5),
              7: FixedColumnWidth(cWidth),
              8: FlexColumnWidth(0.5),
              9: FlexColumnWidth(0.5),
              10: FixedColumnWidth(cWidth),
              11: FlexColumnWidth(0.5),
              12: FlexColumnWidth(0.5),
              13: FixedColumnWidth(cWidth),
              14: FlexColumnWidth(0.5),
              15: FlexColumnWidth(0.5),
              16: FixedColumnWidth(cWidth),
              17: FlexColumnWidth(0.5),
              18: FlexColumnWidth(0.5),
              19: FixedColumnWidth(cWidth),
              20: FlexColumnWidth(0.5),
              21: FlexColumnWidth(0.5),
              22: FixedColumnWidth(cWidth),
              23: FlexColumnWidth(0.5),
              24: FlexColumnWidth(0.5),
              25: FixedColumnWidth(cWidth),
              26: FlexColumnWidth(0.5),
              27: FlexColumnWidth(0.5),
              28: FixedColumnWidth(cWidth),
              29: FlexColumnWidth(0.5),
              30: FlexColumnWidth(0.5),
              31: FixedColumnWidth(cWidth),
              32: FlexColumnWidth(0.5),
              33: FlexColumnWidth(0.5),
              34: FixedColumnWidth(cWidth),
              35: FlexColumnWidth(0.5),
              36: FlexColumnWidth(0.5),
              37: FixedColumnWidth(cWidth),
            },
            children: [
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
              ]),
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[3])),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'p͡ɸ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'b͡β', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'p̪͡f', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'b̪͡v', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 't̪͡θ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'd̪͡ð', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 't͡ɹ̝̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'd͡ɹ̝̠', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 't̠͡ɹ̠̊˔', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'd̠͡ɹ̠˔', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'c͡ç', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɟ͡ʝ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'k͡x', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɡ͡ɣ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'q͡χ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɢ͡ʁ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʡ͡ʜ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʡ͡ʢ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʔ͡h', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
              ]),
            ],
          ),
          Table(columnWidths: {
            0: FixedColumnWidth(rowHeaderLength),
            1: FixedColumnWidth(cWidth),
            2: FixedColumnWidth(cWidth),
            3: FlexColumnWidth(3),
            4: FixedColumnWidth(cWidth),
            5: FixedColumnWidth(cWidth),
            6: FlexColumnWidth(1),
            7: FixedColumnWidth(cWidth),
            8: FlexColumnWidth(1),
            9: FixedColumnWidth(cWidth),
            10: FlexColumnWidth(0.5),
            11: FlexColumnWidth(0.5),
            12: FixedColumnWidth(cWidth),
            13: FlexColumnWidth(0.5),
            14: FlexColumnWidth(0.5),
            15: FixedColumnWidth(cWidth),
            16: FlexColumnWidth(0.5),
            17: FlexColumnWidth(0.5),
            18: FixedColumnWidth(cWidth),
            19: FixedColumnWidth(cWidth),
            20: FlexColumnWidth(4),
            21: FixedColumnWidth(cWidth),
            22: FixedColumnWidth(cWidth),
            23: FixedColumnWidth(cWidth),
          }, children: [
            TableRow(children: [
              Center(child: CLPhHeader(header: rowHeaders[4])),
              DBorder(data: '|'),
              Container(),
              Container(),
              Container(),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 's', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              Container(),
              CPhoneticButton(phonetic: 'z', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ʃ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'ʒ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ʂ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'ʐ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              CPhoneticButton(phonetic: 'ɕ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              CPhoneticButton(phonetic: 'ʑ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
              DBorder(data: '|'),
              Container(),
              Container(),
              Container(),
              Container(),
              DBorder(data: '|'),
            ]),
          ]),
          Table(
            columnWidths: {
              0: FixedColumnWidth(rowHeaderLength),
              1: FixedColumnWidth(cWidth),
              2: FlexColumnWidth(0.5),
              3: FlexColumnWidth(0.5),
              4: FixedColumnWidth(cWidth),
              5: FlexColumnWidth(0.5),
              6: FlexColumnWidth(0.5),
              7: FixedColumnWidth(cWidth),
              8: FlexColumnWidth(0.5),
              9: FlexColumnWidth(0.5),
              10: FixedColumnWidth(cWidth),
              11: FlexColumnWidth(0.5),
              12: FlexColumnWidth(0.5),
              13: FixedColumnWidth(cWidth),
              14: FlexColumnWidth(0.5),
              15: FlexColumnWidth(0.5),
              16: FixedColumnWidth(cWidth),
              17: FlexColumnWidth(0.5),
              18: FlexColumnWidth(0.5),
              19: FixedColumnWidth(cWidth),
              20: FlexColumnWidth(0.5),
              21: FlexColumnWidth(0.5),
              22: FixedColumnWidth(cWidth),
              23: FlexColumnWidth(0.5),
              24: FlexColumnWidth(0.5),
              25: FixedColumnWidth(cWidth),
              26: FlexColumnWidth(0.5),
              27: FlexColumnWidth(0.5),
              28: FixedColumnWidth(cWidth),
              29: FlexColumnWidth(0.5),
              30: FlexColumnWidth(0.5),
              31: FixedColumnWidth(cWidth),
              32: FlexColumnWidth(0.5),
              33: FlexColumnWidth(0.5),
              34: FixedColumnWidth(cWidth),
              35: FlexColumnWidth(0.5),
              36: FlexColumnWidth(0.5),
              37: FixedColumnWidth(cWidth),
            },
            children: [
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
              ]),
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[5])),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ɸ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'β', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'f', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'v', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'θ̼', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ð̼', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'θ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ð', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'θ̠', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ð̠', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ɹ̠̊˔', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɹ̠˔', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ɻ̊˔', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɻ˔', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ç', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʝ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'x', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɣ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'χ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʁ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ħ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʕ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'h', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɦ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
              ]),
            ],
          ),
          Table(
            columnWidths: {
              0: FixedColumnWidth(rowHeaderLength),
              1: FixedColumnWidth(cWidth),
              2: FlexColumnWidth(0.5),
              3: FlexColumnWidth(0.5),
              4: FixedColumnWidth(cWidth),
              5: FlexColumnWidth(1),
              6: FixedColumnWidth(cWidth),
              7: FlexColumnWidth(1),
              8: FixedColumnWidth(cWidth),
              9: FixedColumnWidth(cWidth),
              10: FlexColumnWidth(1.5),
              11: FlexColumnWidth(1.5),
              12: FixedColumnWidth(cWidth),
              13: FixedColumnWidth(cWidth),
              14: FlexColumnWidth(0.5),
              15: FlexColumnWidth(0.5),
              16: FixedColumnWidth(cWidth),
              17: FlexColumnWidth(0.5),
              18: FlexColumnWidth(0.5),
              19: FixedColumnWidth(cWidth),
              20: FlexColumnWidth(0.5),
              21: FlexColumnWidth(0.5),
              22: FixedColumnWidth(cWidth),
              23: FlexColumnWidth(0.5),
              24: FlexColumnWidth(0.5),
              25: FixedColumnWidth(cWidth),
              26: FlexColumnWidth(0.5),
              27: FlexColumnWidth(0.5),
              28: FixedColumnWidth(cWidth),
              29: FlexColumnWidth(0.5),
              30: FlexColumnWidth(0.5),
              31: FixedColumnWidth(cWidth),
            },
            children: [
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[6])),
                DBorder(data: '|'),
                Container(),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʋ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ɹ̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɹ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ɻ̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɻ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'j', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ɰ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ʔ̞', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
              ]),
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[7])),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ⱱ̟', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ⱱ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ɾ̼', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ɾ̥', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɾ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ɽ̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɽ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ɢ̆', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ʡ̆', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[8])),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʙ̥', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʙ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'r̥', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'r', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ɽ̊r̥', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɽr', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʀ̥', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʀ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʜ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʢ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                Container(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[9])),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 't͡ɬ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'd͡ɮ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʈ͡ꞎ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɖ͡ɭ˔', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'c͡ʎ̝̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɟ͡ʎ̝', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'k͡ʟ̝̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɡ͡ʟ̝', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[10])),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ɬ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɮ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ꞎ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɭ˔', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʎ̝̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʎ̝', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʟ̝̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʟ̝', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[11])),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'l̥', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'l', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ɭ̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɭ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʎ̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʎ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʟ̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʟ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ʟ̠̊', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ʟ̠', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                HDash(),
                HDash(),
                DBorder(data: '+'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
              TableRow(children: [
                Center(child: CLPhHeader(header: rowHeaders[12])),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ɺ̥', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɺ', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                Container(),
                DBorder(data: '|'),
                CPhoneticButton(phonetic: 'ɭ̥̆', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                CPhoneticButton(phonetic: 'ɭ̆', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ʎ̆', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                CPhoneticButton(phonetic: 'ʟ̆', phonemes: phonemes, disabled: disabled, onPressed: onPress),
                DBorder(data: '|'),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                Container(),
                DBorder(data: '|'),
              ]),
            ],
          ),
          Table(
            columnWidths: {
              0: FixedColumnWidth(rowHeaderLength),
              1: FixedColumnWidth(cWidth),
              2: FlexColumnWidth(),
              3: FixedColumnWidth(cWidth),
            },
            children: [
              TableRow(children: [HDash(), DBorder(data: '+'), HDash(), DBorder(data: '+')]),
            ],
          ),
        ],
      );
    });
  }
}
